# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: rm -rf yarn.lock node_modules
      - run: yarn install
      - run: curl -sL firebase.tools | bash

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - run: firebase deploy --token "$FIREBASE_TOKEN"
      - run: cd build && git init
      - run: git config user.email koechkevin92@gmail.com
      - run: git add .
      - run: git commit -m "deploy"
      - run: git remote add origin https://github.com/koechkevin/koechkevin.github.io.git
      - run: git push origin master -f -u
